//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAccountant.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAccountant.Shared.Resources.ModelStrings", typeof(ModelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fetch accounts of user..
        /// </summary>
        public static string AccountErrors_CannotFetchAccountsOfUser {
            get {
                return ResourceManager.GetString("AccountErrors_CannotFetchAccountsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authenticated..
        /// </summary>
        public static string AuthenticationErrors_UserNotAuthenticated {
            get {
                return ResourceManager.GetString("AuthenticationErrors_UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string ExpenseSubCategories_Custom {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string ExpenseSubCategories_Electricity {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ExpenseSubCategories_General {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdressing.
        /// </summary>
        public static string ExpenseSubCategories_Hairdressing {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Hairdressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating or Cooling.
        /// </summary>
        public static string ExpenseSubCategories_HeatingOrCooling {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_HeatingOrCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Cleaning.
        /// </summary>
        public static string ExpenseSubCategories_HouseCleaning {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_HouseCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string ExpenseSubCategories_Internet {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Fee.
        /// </summary>
        public static string ExpenseSubCategories_MaintenanceFee {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_MaintenanceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string ExpenseSubCategories_Rent {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent-related.
        /// </summary>
        public static string ExpenseSubCategories_RentRelated {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_RentRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string ExpenseSubCategories_Subscription {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string ExpenseSubCategories_Telephone {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string ExpenseSubCategories_Transportation {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string ExpenseSubCategories_Water {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A credit card was expected..
        /// </summary>
        public static string ImportErrors_AbstractCreditCardExpected {
            get {
                return ResourceManager.GetString("ImportErrors_AbstractCreditCardExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not belong to the authenticated user..
        /// </summary>
        public static string ImportErrors_AccountDoesNotBelongToUser {
            get {
                return ResourceManager.GetString("ImportErrors_AccountDoesNotBelongToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary account ID could not be determined for discovered card number..
        /// </summary>
        public static string ImportErrors_CannotDetermineSecondaryAccount {
            get {
                return ResourceManager.GetString("ImportErrors_CannotDetermineSecondaryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the uploaded statement document..
        /// </summary>
        public static string ImportErrors_CannotParseUploadedStatementFile {
            get {
                return ResourceManager.GetString("ImportErrors_CannotParseUploadedStatementFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the uploaded document..
        /// </summary>
        public static string ImportErrors_CannotSaveUploadedStatementFile {
            get {
                return ResourceManager.GetString("ImportErrors_CannotSaveUploadedStatementFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither of discovered card numbers match the primary card number..
        /// </summary>
        public static string ImportErrors_DiscoveredCardNumbersMismatch {
            get {
                return ResourceManager.GetString("ImportErrors_DiscoveredCardNumbersMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary card number was expected to be discovered by parser..
        /// </summary>
        public static string ImportErrors_PrimaryCardNumberNotDetermined {
            get {
                return ResourceManager.GetString("ImportErrors_PrimaryCardNumberNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A saving account wasn&apos;t expected..
        /// </summary>
        public static string ImportErrors_SavingAccountExpected {
            get {
                return ResourceManager.GetString("ImportErrors_SavingAccountExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary card number was expected to be discovered by parser..
        /// </summary>
        public static string ImportErrors_SecondaryCardNumberNotDetermined {
            get {
                return ResourceManager.GetString("ImportErrors_SecondaryCardNumberNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statement wasn&apos;t of expected type..
        /// </summary>
        public static string ImportErrors_StatementTypeMismatch {
            get {
                return ResourceManager.GetString("ImportErrors_StatementTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of rollover amount, total expenses, fees and debt payments must be equal to total due amount..
        /// </summary>
        public static string ImportErrors_TotalDueAmountMismatch {
            get {
                return ResourceManager.GetString("ImportErrors_TotalDueAmountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement file shouldn&apos;t be empty..
        /// </summary>
        public static string ImportErrors_UploadedStatementFileEmpty {
            get {
                return ResourceManager.GetString("ImportErrors_UploadedStatementFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement file size shouldn&apos;t exceed 1 MB..
        /// </summary>
        public static string ImportErrors_UploadedStatementFileTooBig {
            get {
                return ResourceManager.GetString("ImportErrors_UploadedStatementFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Microsoft Excel workbooks are accepted..
        /// </summary>
        public static string ImportErrors_UploadedStatementFileTypeNotSupported {
            get {
                return ResourceManager.GetString("ImportErrors_UploadedStatementFileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string MainCategory_Expense {
            get {
                return ResourceManager.GetString("MainCategory_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string MainCategory_Income {
            get {
                return ResourceManager.GetString("MainCategory_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest or Fee.
        /// </summary>
        public static string MainCategory_InterestOrFee {
            get {
                return ResourceManager.GetString("MainCategory_InterestOrFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string MainCategory_Loan {
            get {
                return ResourceManager.GetString("MainCategory_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MainCategory_None {
            get {
                return ResourceManager.GetString("MainCategory_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string MainCategory_Saving {
            get {
                return ResourceManager.GetString("MainCategory_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card numbers are in unexpected format..
        /// </summary>
        public static string ParserErrors_CardNumbersInUnexpectedFormat {
            get {
                return ResourceManager.GetString("ParserErrors_CardNumbersInUnexpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipart statement couldn&apos;t be read..
        /// </summary>
        public static string ParserErrors_CouldNotReadMultipartStatement {
            get {
                return ResourceManager.GetString("ParserErrors_CouldNotReadMultipartStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement couldn&apos;t be read..
        /// </summary>
        public static string ParserErrors_CouldNotReadStatement {
            get {
                return ResourceManager.GetString("ParserErrors_CouldNotReadStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated deflection amount is larger than allowed absolute threshold..
        /// </summary>
        public static string ParserErrors_DeflectionTooLarge {
            get {
                return ResourceManager.GetString("ParserErrors_DeflectionTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized file format. Column count was expected to be at least 5..
        /// </summary>
        public static string ParserErrors_InsufficientColumnCount {
            get {
                return ResourceManager.GetString("ParserErrors_InsufficientColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount of transactions and the remaining balance do not match..
        /// </summary>
        public static string ParserErrors_TransactionAmountAndBalanceMismatch {
            get {
                return ResourceManager.GetString("ParserErrors_TransactionAmountAndBalanceMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount of transactions and the due amount do not match..
        /// </summary>
        public static string ParserErrors_TransactionAmountAndTotalExpensesMismatch {
            get {
                return ResourceManager.GetString("ParserErrors_TransactionAmountAndTotalExpensesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized file format. Expected to have transaction date at column A..
        /// </summary>
        public static string ParserErrors_TransactionDateColumnMissing {
            get {
                return ResourceManager.GetString("ParserErrors_TransactionDateColumnMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction doesn&apos;t have a valid amount value..
        /// </summary>
        public static string ParserErrors_UnexpectedAmountFormat {
            get {
                return ResourceManager.GetString("ParserErrors_UnexpectedAmountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card statement has an unexpected format..
        /// </summary>
        public static string ParserErrors_UnexpectedCreditCardStatementFormat {
            get {
                return ResourceManager.GetString("ParserErrors_UnexpectedCreditCardStatementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized date format. Could not parse transaction date..
        /// </summary>
        public static string ParserErrors_UnexpectedDateFormat {
            get {
                return ResourceManager.GetString("ParserErrors_UnexpectedDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit statement has an unexpected format..
        /// </summary>
        public static string ParserErrors_UnexpectedDebitStatementFormat {
            get {
                return ResourceManager.GetString("ParserErrors_UnexpectedDebitStatementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement was expected to be consist of 2 parts..
        /// </summary>
        public static string ParserErrors_UnexpectedPartCount {
            get {
                return ResourceManager.GetString("ParserErrors_UnexpectedPartCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction doesn&apos;t have a valid remaining amount value..
        /// </summary>
        public static string ParserErrors_UnexpectedRemainingAmountFormat {
            get {
                return ResourceManager.GetString("ParserErrors_UnexpectedRemainingAmountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a sheet in the document..
        /// </summary>
        public static string ParserErrors_UploadedDocumentMissingSheet {
            get {
                return ResourceManager.GetString("ParserErrors_UploadedDocumentMissingSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalized.
        /// </summary>
        public static string ProvisionState_Finalized {
            get {
                return ResourceManager.GetString("ProvisionState_Finalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Provision.
        /// </summary>
        public static string ProvisionState_Open {
            get {
                return ResourceManager.GetString("ProvisionState_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Azure blob storage-related exception occurred..
        /// </summary>
        public static string StorageErrors_AzureStorageError {
            get {
                return ResourceManager.GetString("StorageErrors_AzureStorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists in destination..
        /// </summary>
        public static string StorageErrors_FileAlreadyExists {
            get {
                return ResourceManager.GetString("StorageErrors_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed..
        /// </summary>
        public static string StorageErrors_UploadFailed {
            get {
                return ResourceManager.GetString("StorageErrors_UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not belong to user..
        /// </summary>
        public static string TransactionErrors_AccountDoesNotBelongToUser {
            get {
                return ResourceManager.GetString("TransactionErrors_AccountDoesNotBelongToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        public static string TransactionErrors_AccountNotFound {
            get {
                return ResourceManager.GetString("TransactionErrors_AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching transactions of the account..
        /// </summary>
        public static string TransactionErrors_CannotFetchTransactionsOfAccount {
            get {
                return ResourceManager.GetString("TransactionErrors_CannotFetchTransactionsOfAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the credit card transaction..
        /// </summary>
        public static string TransactionErrors_CannotUpdateCreditCardTransaction {
            get {
                return ResourceManager.GetString("TransactionErrors_CannotUpdateCreditCardTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the debit transaction..
        /// </summary>
        public static string TransactionErrors_CannotUpdateDebitTransaction {
            get {
                return ResourceManager.GetString("TransactionErrors_CannotUpdateDebitTransaction", resourceCulture);
            }
        }
    }
}
