//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAccountant.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAccountant.Shared.Resources.ModelStrings", typeof(ModelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string ExpenseSubCategories_Custom {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string ExpenseSubCategories_Electricity {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ExpenseSubCategories_General {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hairdressing.
        /// </summary>
        public static string ExpenseSubCategories_Hairdressing {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Hairdressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating or Cooling.
        /// </summary>
        public static string ExpenseSubCategories_HeatingOrCooling {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_HeatingOrCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Cleaning.
        /// </summary>
        public static string ExpenseSubCategories_HouseCleaning {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_HouseCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string ExpenseSubCategories_Internet {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Fee.
        /// </summary>
        public static string ExpenseSubCategories_MaintenanceFee {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_MaintenanceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string ExpenseSubCategories_Rent {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent-related.
        /// </summary>
        public static string ExpenseSubCategories_RentRelated {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_RentRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string ExpenseSubCategories_Subscription {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string ExpenseSubCategories_Telephone {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string ExpenseSubCategories_Transportation {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string ExpenseSubCategories_Water {
            get {
                return ResourceManager.GetString("ExpenseSubCategories_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string MainCategory_Expense {
            get {
                return ResourceManager.GetString("MainCategory_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string MainCategory_Income {
            get {
                return ResourceManager.GetString("MainCategory_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest or Fee.
        /// </summary>
        public static string MainCategory_InterestOrFee {
            get {
                return ResourceManager.GetString("MainCategory_InterestOrFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string MainCategory_Loan {
            get {
                return ResourceManager.GetString("MainCategory_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MainCategory_None {
            get {
                return ResourceManager.GetString("MainCategory_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string MainCategory_Saving {
            get {
                return ResourceManager.GetString("MainCategory_Saving", resourceCulture);
            }
        }
    }
}
