// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SmartAccountant.Repositories.Core.Migrations
{
    /// <inheritdoc />
    internal partial class MoveTransactionsUnderAccount : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            //NOTE: Delete any existing Transaction from database before begin.

            migrationBuilder.DropForeignKey(
                name: "FK_Transactions_Statements_StatementId",
                table: "Transactions");

            migrationBuilder.DropIndex(
                name: "IX_Transactions_StatementId",
                table: "Transactions");

            migrationBuilder.DropColumn(
                name: "Order",
                table: "DebitTransactions");

            migrationBuilder.DropColumn(
                name: "StatementId",
                table: "Transactions");

            migrationBuilder.AddColumn<Guid>(
                name: "AccountId",
                table: "Transactions",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: Guid.Empty);

            migrationBuilder.CreateIndex(
                name: "IX_Transactions_AccountId",
                table: "Transactions",
                column: "AccountId");

            migrationBuilder.CreateIndex(
                name: "IX_Transactions_AccountId_ReferenceNumber",
                table: "Transactions",
                columns: new[] { "AccountId", "ReferenceNumber" },
                unique: true,
                filter: "[ReferenceNumber] IS NOT NULL");

            migrationBuilder.AddForeignKey(
                name: "FK_Transactions_Accounts_AccountId",
                table: "Transactions",
                column: "AccountId",
                principalTable: "Accounts",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            throw new NotSupportedException();
        }
    }
}
