// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SmartAccountant.Repositories.Core.Migrations
{
    /// <inheritdoc />
    public partial class AddMonthlySummary : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MonthlySummaries",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    UserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Month = table.Column<DateOnly>(type: "date", nullable: false),
                    State = table.Column<byte>(type: "tinyint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MonthlySummaries", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "CurrencySummary",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    MonthlySummaryId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    RemainingBalancesTotal = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    RemainingBalancesTotalCurrency = table.Column<short>(type: "smallint", nullable: false),
                    OriginalLimitsTotal = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    OriginalLimitsTotalCurrency = table.Column<short>(type: "smallint", nullable: false),
                    IncomeTotal = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    IncomeTotalCurrency = table.Column<short>(type: "smallint", nullable: false),
                    ExpensesTotal = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    ExpensesTotalCurrency = table.Column<short>(type: "smallint", nullable: false),
                    InterestAndFeesTotal = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    InterestAndFeesTotalCurrency = table.Column<short>(type: "smallint", nullable: false),
                    PlannedExpensesTotal = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    PlannedExpensesTotalCurrency = table.Column<short>(type: "smallint", nullable: false),
                    LoansTotal = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    LoansTotalCurrency = table.Column<short>(type: "smallint", nullable: false),
                    SavingsTotal = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    SavingsTotalCurrency = table.Column<short>(type: "smallint", nullable: false),
                    Net = table.Column<decimal>(type: "decimal(19,4)", nullable: false),
                    NetCurrency = table.Column<short>(type: "smallint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CurrencySummary", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CurrencySummary_MonthlySummaries_MonthlySummaryId",
                        column: x => x.MonthlySummaryId,
                        principalTable: "MonthlySummaries",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CurrencySummary_MonthlySummaryId",
                table: "CurrencySummary",
                column: "MonthlySummaryId");

            migrationBuilder.CreateIndex(
                name: "IX_MonthlySummaries_UserId_Month",
                table: "MonthlySummaries",
                columns: new[] { "UserId", "Month" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CurrencySummary");

            migrationBuilder.DropTable(
                name: "MonthlySummaries");
        }
    }
}
