//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAccountant.Repositories.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAccountant.Repositories.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove transactions..
        /// </summary>
        internal static string CannotDeleteTransactions {
            get {
                return ResourceManager.GetString("CannotDeleteTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch account ({0})..
        /// </summary>
        internal static string CannotFetchAccount {
            get {
                return ResourceManager.GetString("CannotFetchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch accounts of user ({0})..
        /// </summary>
        internal static string CannotFetchAccountsOfUser {
            get {
                return ResourceManager.GetString("CannotFetchAccountsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch credit card limits for user ({0})..
        /// </summary>
        internal static string CannotFetchCreditCardLimitsForUser {
            get {
                return ResourceManager.GetString("CannotFetchCreditCardLimitsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch transactions of account ({0})..
        /// </summary>
        internal static string CannotFetchTransactionsOfUser {
            get {
                return ResourceManager.GetString("CannotFetchTransactionsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch transactions of user ({0}) for month ({1})..
        /// </summary>
        internal static string CannotFetchTransactionsOfUserForMonth {
            get {
                return ResourceManager.GetString("CannotFetchTransactionsOfUserForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert statement ({0})..
        /// </summary>
        internal static string CannotInsertStatement {
            get {
                return ResourceManager.GetString("CannotInsertStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert transactions..
        /// </summary>
        internal static string CannotInsertTransactions {
            get {
                return ResourceManager.GetString("CannotInsertTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update credit card transaction ({0})..
        /// </summary>
        internal static string CannotUpdateCreditCardTransaction {
            get {
                return ResourceManager.GetString("CannotUpdateCreditCardTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update debit transaction ({0})..
        /// </summary>
        internal static string CannotUpdateDebitTransaction {
            get {
                return ResourceManager.GetString("CannotUpdateDebitTransaction", resourceCulture);
            }
        }
    }
}
