//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAccountant.Import.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAccountant.Import.Service.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking the existing transactions of the account ({0})..
        /// </summary>
        internal static string CannotCheckExistingTransactions {
            get {
                return ResourceManager.GetString("CannotCheckExistingTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary account ID could not be determined for discovered card number ({0})..
        /// </summary>
        internal static string CannotDetermineSecondaryAccount {
            get {
                return ResourceManager.GetString("CannotDetermineSecondaryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while importing the statement ({0}) to account ({1})..
        /// </summary>
        internal static string CannotImportStatement {
            get {
                return ResourceManager.GetString("CannotImportStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the uploaded statement document for account ({0})..
        /// </summary>
        internal static string CannotParseUploadedStatementFile {
            get {
                return ResourceManager.GetString("CannotParseUploadedStatementFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while persisting the statement being imported for account ({0})..
        /// </summary>
        internal static string CannotSaveImportingStatement {
            get {
                return ResourceManager.GetString("CannotSaveImportingStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the uploaded document (AccountId: {0})..
        /// </summary>
        internal static string CannotSaveUploadedStatementFile {
            get {
                return ResourceManager.GetString("CannotSaveUploadedStatementFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while verifying the holder of account ({0})..
        /// </summary>
        internal static string CannotValidateAccountHolder {
            get {
                return ResourceManager.GetString("CannotValidateAccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither of discovered card numbers ({0}, {1}) match primary card number ({2})..
        /// </summary>
        internal static string DiscoveredCardNumbersMismatch {
            get {
                return ResourceManager.GetString("DiscoveredCardNumbersMismatch", resourceCulture);
            }
        }
    }
}
